name: Render Backend Warm-Up

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  warm_up:
    name: Ping Health Endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Health
        run: |
          echo "UTC Time: $(date -u)"
          curl -w "\nResponse Time: %{time_total}s\nHTTP Status: %{http_code}\n" -L -s https://attendance-system-backend-unu2.onrender.com/api/health

